name = "driver-financial-manager-api"
main = "src/index.ts"
compatibility_date = "2025-01-20"

[durable_objects]
bindings = [
  { name = "DB", class_name = "MoneyManagerDB", script_name = "driver-financial-manager-api" }
]

[[migrations]]
tag = "v1"
new_classes = ["MoneyManagerDB"]

[env.production]
route = { pattern = "api.driver-finance.pages.dev/*", zone_name = "driver-finance.pages.dev" }

[env.production.vars]
ENVIRONMENT = "production"
